# Generated by Django 5.2 on 2025-04-09 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория аты')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Слаг (автоматтык)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Аты')),
                ('description', models.TextField(blank=True, verbose_name='Сүрөттөмөсү')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Баасы (сом)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Сүрөтү')),
                ('is_special', models.BooleanField(default=False, verbose_name='Өзгөчө сунуш?')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Меню пункту',
                'verbose_name_plural': 'Меню пункттары',
                'ordering': ['category', 'name'],
            },
        ),
    ]
